### ISSUE TITLE
Nerve-racking: running "Your first script" does not show output (as of version 1.1.171)

### ISSUE THREAD

**Issue by rogererens** [braveclojure/babooka#10]
Although it is feels **Victorious** to see that running `bb hello.clj` does not result in any error, it is slightly less so, as you seem to insist that the text `"Hello inner world!"` ought to be printed.
Since babashka version 1.1.171 included a [breaking change](https://github.com/babashka/babashka/blob/master/CHANGELOG.md#breaking-changes) to make printing results an opt-in, the flag `--prn` should be used to have such text thrown into the world at large.

**Comment by borkdude** [comment]
Also reported in #7

**Comment by rogererens** [comment]
Fixed in commit 5060609 by surrounding `str/join` with a `prn`
